# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Playwright Automation
on:
    workflow_dispatch:
        inputs:
            ENV:
                type: choice
                description: Environment
                default: "stg"
                options:
                    - stg
                    - prod
    schedule:
        - cron: "15 * * * *"
    push:
        branches: ["main"]
env:
    ENV: ${{ inputs.ENV || github.event.schedule == '15 * * * *' && 'prod' || 'stg' }}
    GCP_PROJECT_ID: winn-ai-general
jobs:
    load-testing:
        runs-on: ubuntu-latest
        # strategy:
        #     matrix:
        #         users:
        #         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v3

            - run: |
                  echo "${{ env.ENV }}"

            # - run: |
            #     echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
            #     cat ./package.json >> $GITHUB_ENV
            #     echo 'EOF' >> $GITHUB_ENV
            # - run: |
            #     echo '${{ fromJson(env.PACKAGE_JSON).version }}'
            # - name: get version
            #   id: users
            #   uses: notiz-dev/github-action-json-property@release
            #   with:
            #     path: 'users.json'
            #     prop_path: 'users'
            # - run: echo ${{steps.users.outputs.prop}}
            # - name: Build
            #   run: bash scripts/build.sh
